---
title: "C.V."
knit: (function(inputFile, encoding) {
      out_dir <- "docs";
      rmarkdown::render(inputFile,
                        encoding=encoding,
                        output_dir=file.path(dirname(inputFile), out_dir))})
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

------------------------------------------------------------------------

## **EDUCATION**

------------------------------------------------------------------------

Ph.D. Economics, Middle Tennessee State University, Murfreesboro, TN (Expected August 2026)

M.A. Economics, Middle Tennessee State University, Murfreesboro, TN (2025)

B.S. Mathematical Economics & Philosophy, *magna cum laude*, Hampden-Sydney College, Hampden Sydney, VA (2023)

## **EXPERIENCE**

------------------------------------------------------------------------

-   **Defense Logistics Agency -- Aviation, Richmond, VA ---** May 2021 -- Current
    -   *Post-Award Contract Specialist (Trainee)*
        -   Received comprehensive cradle-to-grave government contracting training (FAR/DFARS) with hands-on proficiency in information systems including SAP EBS, WAWF, and federal records management

        -   Collaborated with Subject Matter Experts (SMEs) and OEM vendors to resolve government contract discrepancies and ensure compliance/technical alignment
-   **Tyger Strategies Consulting Group, Midlothian, VA (Remote) ---** June 2020 -- August 2020
    -   *Business Analyst Intern*
        -   Performed market research and data analysis for a 501(c)(3) nonprofit consulting group
        -   Developed and presented actionable marketing and strategic recommendations to clients

## **RESEARCH INTERESTS**

------------------------------------------------------------------------

Historical Political Economy, Public Choice Theory, Austrian Economics, Public Interest Regulation

## **WORKING PAPERS**

------------------------------------------------------------------------

*“The Father of Food and Drug Law as Strategic Regulator: Dr. Harvey Wiley and the Political Economy of the Bottled-In-Bond Act”*

*“Bank Runs without a Cause: Frequency, Contagion, and Mitigation Measures in the U.S., 1889-1929”*

*“Alms and Ale: A Malthusian Test of Welfare Generosity and Alcohol Consumption in OECD Countries, 1995–2023”*

*“Assuring Consumers of Authenticity, Safety, & Quality in Early American Whiskey Markets”*

## **ACADEMIC CONFERENCE PAPERS**

------------------------------------------------------------------------

"Bottled in Bondage", *Southern Economic Association Annual Meeting*. Fort Lauderdale, Florida, November 19-21, 2022

"Distillers and Chemists: Strategic use of the Bottled-In-Bond Act of 1897 by both firms and regulators", *Public Choice Society Meetings*. Plano, Texas, March 14-16, 2024

"Distillers and Chemists: Strategic use of the Bottled-In-Bond Act of 1897 by both firms and regulators", *Southern Economic Association Annual Meeting*.  Washington, DC, November 23-25, 2024

“The Father of Food and Drug Law as Strategic Regulator: Dr. Harvey Wiley and the Political Economy of the Bottled-In-Bond Act*” Public Choice Society Meetings.* Louisville, Kentucky, March 6-8, 2025

“The Father of Food and Drug Law as Strategic Regulator: Dr. Harvey Wiley and the Political Economy of the Bottled-In-Bond Act*” Law & Economics with Public Choice Insights Workshop, Stephenson Institute for Classical Liberalism.* Tampa, Florida, November 19-22, 2025

“Panic Before Protection: Bank Runs, Contagion, and Mitigation Measures in the United States, 1889-1929”, *Southern Economic Association Annual Meeting*. Tampa, Florida, November 22-24, 2025

“Alms and Ale: A Malthusian Test of Welfare Generosity and Alcohol Consumption in OECD Countries, 1995–2023”, *Southern Economic Association Annual Meeting*. Tampa, Florida, November 22-24, 2025

“Bank Runs, Contagion, and Mitigation Measures in the United States, 1889–1919*” INET-YSI-University of Lyon 2 Workshop*. Lyon, France, December 11-12, 2025

## **COLLOQUIA & SEMINARS ATTENDED**

------------------------------------------------------------------------

Public Choice Outreach Conference, *Center for Study of Public Choice*, GMU (2023)

Harwood Graduate Colloquium on Public Choice, *American Institute for Economic Research* (2024)

Harwood Graduate Colloquium on Defending Classical Liberalism, *AIER* (2025)

Summer Seminar on Classical Liberalism and Business, *AIER*, UIC (2025)

Summer Seminar on Classical Liberalism and The Market, *AIER*, UIS (2025)

Summer Seminar on Classical Liberalism, *AIER*, Wabash College (2025)

Economic Freedom Research Colloquium, *Bridwell Institute*, SMU Cox (2025)

## **AWARDS, FELLOWSHIPS, AND GRANTS**

------------------------------------------------------------------------

Political Economy Research Institute Ph.D. Summer Fellowship, \$5,000 (Summer 2024, 2025)

Economic Freedom Research Colloquium Honorarium, Bridwell Institute, \$3000 (2025)

Center for the Study of Political Economy Fellowship (2019-2023)

Pi Mu Epsilon, US Honorary Mathematics Society (2022)

## **TEACHING EXPERIENCE**

------------------------------------------------------------------------

**Principles of Microeconomics, Middle Tennessee State University (2025)**

Selected Student Comments (Informal Evaluation)

-   “Micro Econ with Professor Smith has been a pleasure. He is great at talking through the chapters with everyone and provides lots of help and assistance if needed. I would recommend this class to others.”

-   “I enjoyed this class. You’re great at explaining things that don’t make sense to me the first time. I like the interactive activities that allow me to visualize the topic.”

-   “Overall, I appreciate how well-knowledgeable the professor is and how he teaches in a way students can understand. Will be taking him for Macro next semester.”

-   “Every lesson was given with clear instruction and he answered every student’s question with a detailed, clear response… overall excellent course and I would take it again.”

-   “You give good examples; your lectures are usually very easy to follow. Exams have a good format and you give excellent resources for studying. Overall, I have really enjoyed having you as my professor.”

-   “This class helped me take my knowledge about economics even further. Jacob Smith makes it easy to understand challenging topics and provides great examples with real-world correlations.”

## **SERVICE AND LEADERSHIP**

------------------------------------------------------------------------

H-SC Student Honor Court Investigator, 2022-2023

H-SC *Journal of the Sciences* Editor, Vol. XVII

Alpha Chi Sigma Beta Chi Chapter Vice Master Alchemist (2022) and Historian (2023)

Atkinson Museum Student Museum Board Member, 2022-2023

Union Philanthropic Literary Society Junior Member, 2021-2023

Undergraduate Philosophical Association of Virginia Member, 2022-2023

Wilson Center's Leadership in the Public Interest Four-Year Program Member, 2019-2023
