---
knit: (function(inputFile, encoding) {
      out_dir <- "docs";
      rmarkdown::render(inputFile,
                        encoding=encoding,
                        output_dir=file.path(dirname(inputFile), out_dir))})
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

# Jacob R. Smith

## Welcome to My Professional Website

Hello! I am Jacob Smith, a first-year Economics PhD student at Middle Tennessee State University with interest in Public Choice and Regulation. On this website, you can find information about my resume, publications, and research.

### Contact Information

- **LinkedIn:** [Your LinkedIn Profile](https://https://www.linkedin.com/in/jacobsmithr)
- **Email:** [jacob.rand.smith@gmail.com](mailto:jacob.rand.smith@gmail.com)

### Working Papers

1. Smith, Jacob. *Distillers and Chemists: Strategic use of the Bottled-In-Bond Act of 1897 by both firms and regulators*

### About Me

I am currently a graduate teaching assistant and first-year Ph.D. student in Economics at Middle Tennessee State University's Jones College of Business. I am also a Summer 2024 Fellow with MTSU's Political Economy Research Institute (PERI).

I graduated Magna Cum Laude from Hampden-Sydney College in 2023 with a Bachelor of Science in Mathematical Economics and a second major in Philosophy.

- [Resume](resume.html)
- [Publications](publications.html)
- [Research](research.html)