---
knit: (function(inputFile, encoding) {
      out_dir <- "docs";
      rmarkdown::render(inputFile,
                        encoding=encoding,
                        output_dir=file.path(dirname(inputFile), out_dir))})
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## **Working Papers**

1.  Smith, Jacob. *Distillers and Chemists: Strategic use of the Bottled-In-Bond Act of 1897 by both firms and regulators*

> "The Bottled-In-Bond Act of 1897 (BiB), one of the first consumer protection regulations in the United States, is commonly thought to safeguard consumers from harmful whiskey makers and adulterated whiskey, which were allegedly common practices in the late 19^th^ and early 20^th^ century. The BiB restricted the labeling of whiskey bottles and attempted to guarantee the quality of liquor. While there is no evidence of any consumer being harmed from adulterated or rectified whiskey, alternative explanations for the BiB are wanting.
>
> Contrary to common wisdom, the BiB served a combination of private interests, namely, incumbent aged whiskey distillers and federal regulators. Aged whiskey distillers took advantage of the labeling rules imposed by the BiB in their advertisements, which conveyed signals of quality and credibility from a government authority, e.g., green bottled-in-bond stamps. Fear and uncertainty, combined with public exhibitions and expert statements to promote Bottled-In-Bond whiskey, were cited in advertisements by aged whiskey distillers to shift consumer preferences away from rectified whiskey and towards aged whiskey. Government officials were incentivized to promote bottled-in-bond whiskey and promulgate concern about adulterants in rectified whiskey in order to expand their bureau and secure additional appropriations. I will outline relevant economic theory on rent seeking and market uncertainty and apply it to the Progressive Era whiskey market. I will then show historical evidence of both specific firms and regulators attempting to promulgate consumer uncertainty over quality and reaping the benefits of assuaging consumers\' fear. "
